# Generated by Django 3.1.4 on 2022-06-25 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_title', models.CharField(max_length=50)),
                ('new_topic_title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SubTopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_topic_title', models.CharField(max_length=50)),
                ('stopic_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='READING.topic')),
            ],
        ),
    ]
