# Generated by Django 3.1.4 on 2022-06-11 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VIDEO', '0002_auto_20220611_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='video_image',
            field=models.ImageField(default='', upload_to='VIDEO/VIDEOS'),
        ),
    ]
