# Generated by Django 3.1.4 on 2022-06-11 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VIDEO', '0003_video_video_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_image',
            field=models.ImageField(default='', upload_to='VIDEO/VIDEO-IMAGE'),
        ),
    ]
