# Generated by Django 3.1.4 on 2022-06-15 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VIDEO', '0005_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='topic_duration',
            field=models.FloatField(default=None),
        ),
        migrations.AlterField(
            model_name='topic',
            name='topic_instructors_name',
            field=models.CharField(default=None, max_length=400),
        ),
    ]
