# Generated by Django 3.1.4 on 2022-06-15 17:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VIDEO', '0006_auto_20220615_2022'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parts_Of_Speech',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Parts_Of_Speech_title', models.CharField(max_length=250)),
                ('Parts_Of_Speech_instructor_name', models.CharField(max_length=100)),
                ('Parts_Of_Speech_duration', models.FloatField(default=0.0)),
                ('Parts_Of_Speech_image', models.ImageField(default='', upload_to='VIDEO/VIDEO-IMAGE')),
                ('Parts_Of_Speech', models.FileField(null=True, upload_to='VIDEO/VIDEOS', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv'])])),
            ],
        ),
        migrations.DeleteModel(
            name='Video',
        ),
    ]
