# Generated by Django 3.1.4 on 2022-06-15 17:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VIDEO', '0007_auto_20220615_2303'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Article_title', models.CharField(max_length=250)),
                ('Article_instructor_name', models.CharField(max_length=100)),
                ('Article_duration', models.FloatField(default=0.0)),
                ('Article_image', models.ImageField(default='', upload_to='VIDEO/ARTICLE/VIDEO-IMAGE')),
                ('Article', models.FileField(null=True, upload_to='VIDEO/ARTICLE/VIDEOS', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv'])])),
            ],
        ),
        migrations.CreateModel(
            name='Error_and_Omission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Error_and_Omission_title', models.CharField(max_length=250)),
                ('Error_and_Omission_instructor_name', models.CharField(max_length=100)),
                ('Error_and_Omission_duration', models.FloatField(default=0.0)),
                ('Error_and_Omission_image', models.ImageField(default='', upload_to='VIDEO/ERROR-AND-OMMISION/VIDEO-IMAGE')),
                ('Error_and_Omission', models.FileField(null=True, upload_to='VIDEO/ERROR-AND-OMMISION/VIDEOS', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv'])])),
            ],
        ),
        migrations.CreateModel(
            name='Jumbled_Sentence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Jumbled_Sentence_title', models.CharField(max_length=250)),
                ('Jumbled_Sentence_instructor_name', models.CharField(max_length=100)),
                ('Jumbled_Sentence_duration', models.FloatField(default=0.0)),
                ('Jumbled_Sentence_image', models.ImageField(default='', upload_to='VIDEO/JUMBLED-SENTENCES/VIDEO-IMAGE')),
                ('Jumbled_Sentence', models.FileField(null=True, upload_to='VIDEO/JUMBLED-SENTENCES/VIDEOS', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv'])])),
            ],
        ),
        migrations.AlterField(
            model_name='parts_of_speech',
            name='Parts_Of_Speech',
            field=models.FileField(null=True, upload_to='VIDEO/PARTS-OF-SPEECH/VIDEOS', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv'])]),
        ),
        migrations.AlterField(
            model_name='parts_of_speech',
            name='Parts_Of_Speech_image',
            field=models.ImageField(default='', upload_to='VIDEO/PARTS-OF-SPEECH/VIDEO-IMAGE'),
        ),
    ]
