# Generated by Django 3.1.4 on 2022-06-15 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VIDEO', '0008_auto_20220615_2328'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Error_and_Omission',
            new_name='Errors_and_Omission',
        ),
    ]
