# Generated by Django 3.1.4 on 2022-06-17 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VIDEO', '0009_auto_20220615_2329'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='Article_title',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='errors_and_omission',
            old_name='Error_and_Omission_title',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='jumbled_sentence',
            old_name='Jumbled_Sentence_title',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='parts_of_speech',
            old_name='Parts_Of_Speech_title',
            new_name='title',
        ),
    ]
