# Generated by Django 3.1.4 on 2022-06-17 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VIDEO', '0011_auto_20220617_2243'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='Article_duration',
            new_name='duration',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='Article_image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='Article_instructor_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='errors_and_omission',
            old_name='Error_and_Omission_duration',
            new_name='duration',
        ),
        migrations.RenameField(
            model_name='errors_and_omission',
            old_name='Error_and_Omission_image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='errors_and_omission',
            old_name='Error_and_Omission_instructor_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='jumbled_sentence',
            old_name='Jumbled_Sentence_duration',
            new_name='duration',
        ),
        migrations.RenameField(
            model_name='jumbled_sentence',
            old_name='Jumbled_Sentence_image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='jumbled_sentence',
            old_name='Jumbled_Sentence_instructor_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='parts_of_speech',
            old_name='Parts_Of_Speech_duration',
            new_name='duration',
        ),
        migrations.RenameField(
            model_name='parts_of_speech',
            old_name='Parts_Of_Speech_image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='parts_of_speech',
            old_name='Parts_Of_Speech_instructor_name',
            new_name='name',
        ),
    ]
